<h1><center>IST 597 Foundations of Deep Learning</center></h1>

---

<h2><center>Assignment 01</center><h2>

**Instructor** : Dr. C. Lee Giles <br>
**TA** : Neisarg Dave, Shaurya Rohatgi
<br><br>

Credits: Thanks and credits to materials from UCL and GeorgiaTech

<h3>Course Policy<h3>

Carefully read all the instructions, before you start working on the assignment

* Give maximum explanation for each sub-problems.

* Assignments are due before class at Monday 05:59:59 pm. Please check the due date on the official course webportalg Portal.

* Please avoid single line answers, submissions without any explanations would receive 0 points.

* Late submissions will be graded with 20% discount per day. Day 1 starts immediately after the submission deadline.

* Every assignment has a hard deadline, usually 3 days past the original due date, i.e. Thursday after the due Monday

* Late submissions (penalty or not) are not accepted after the hard deadline.

* All source materials must be cited. The University Academic Code of Conduct will be strictly enforced.

* We will be creating Canvas submission page for this. Submit all files on Canvas.

* All queries related to Assignment should have a subject line *IST597:Assignment_01 Queries*

---



In [ ]:
#@
Name = "Akshaya Jayant Patil"#@param {type:"string"}
PSU_ID = "935348113"#@param {type:"string"}

### Problem 1
--------------

Let $ \ T:\mathbb{R}^3 \rightarrow \mathbb{R}^4$ be defined by \
$$ Tx = \begin{bmatrix}
x_1 - 3x_3 \\
x_1+x_2 -6x_3 \\
x_2-3x_3 \\
x_1 - 3x_3
\end{bmatrix} $$

for every $x = \begin{bmatrix} x_1 \\ x_2 \\ x_3 \end{bmatrix} \in \mathbb{R}^3$ Then, 


1) Write $\ T$ in matrix form.


*answer* : 
> Given: 
>>-> $𝑇: ℝ^3 → ℝ^4$

>>-> $ Tx =  
\begin{bmatrix}
x_1 - 3x_3 \\
x_1 + x_2 - 6x_3 \\
x_2 - 3x_3 \\
x_1 - 3x_3 \\
\end{bmatrix}$

>>->  $x = \begin{bmatrix}
  x_1 \\
  x_2 \\
  x_3 \\
  \end{bmatrix}
  \in  ℝ^3$

>Therefore,

>>  $ T   
  \begin{bmatrix}
  x_1 \\
  x_2 \\
  x_3 \\
  \end{bmatrix}_{3,1}
  =  
  \begin{bmatrix}
  x_1 - 3x_3 \\
  x_1 + x_2 - 6x_3 \\
  x_2 - 3x_3 \\
  x_1 - 3x_3 \\
  \end{bmatrix}_{4,1}$

>As per the matrix multiplication rule, T matrix must be of size 4 x 3

>>$ x_1 
\begin{bmatrix}
 \cdots \\
 \cdots \\
 \cdots \\
 \cdots \\
 \end{bmatrix}
 +x_2 
\begin{bmatrix}
 \cdots \\
 \cdots \\
 \cdots \\
 \cdots \\
 \end{bmatrix}
 +
 x_3 
\begin{bmatrix}
 \cdots \\
 \cdots \\
 \cdots \\
 \cdots \\
 \end{bmatrix}
 =
 \begin{bmatrix}
  x_1 - 3x_3 \\
  x_1 + x_2 - 6x_3 \\
  x_2 - 3x_3 \\
  x_1 - 3x_3 \\
  \end{bmatrix}$

>By comparing coefficients,

>>$ x_1 
\begin{bmatrix}
 1 \\
 1 \\
 0 \\
 1 \\
 \end{bmatrix}
 +x_2 
\begin{bmatrix}
 0 \\
 1 \\
 1 \\
 0 \\
 \end{bmatrix}
 +
 x_3 
\begin{bmatrix}
 -3 \\
 -6 \\
 -3 \\
 -3 \\
 \end{bmatrix}
 =
 \begin{bmatrix}
  x_1 - 3x_3 \\
  x_1 + x_2 - 6x_3 \\
  x_2 - 3x_3 \\
  x_1 - 3x_3 \\
  \end{bmatrix}$

>**Final Answer:**

>>>$ T = 
 \begin{bmatrix}
 1 & 0 & -3 \\
 1 & 1 & -6 \\
 0 & 1 & -3 \\
 1 & 0 & -3 \\
\end{bmatrix}$

2) $T(3, -2, 4)$ 

*answer* : 

>Given
>>$x = \begin{bmatrix}
  x_1 \\
  x_2 \\
  x_3 \\
  \end{bmatrix} \in ℝ^3$

>>Therefore, $x_1= 3, x_2= -2, x_3= 4$

>$T(3,-2,4) =   
  \begin{bmatrix}
  x_1 - 3x_3 \\
  x_1 + x_2 - 6x_3 \\
  x_2 - 3x_3 \\
  x_1 - 3x_3 \\
  \end{bmatrix}$

>$T(3,-2,4)  =  
  \begin{bmatrix}
  3 - 3 (4) \\
  3 + (-2) - 6(4) \\
  -2 - 3(4) \\
  3 - 3(4) \\
  \end{bmatrix}$

>**Final Answer**
>>> $T(3,-2,4)  =  
  \begin{bmatrix}
  -9 \\
  -23 \\
  -14 \\
  -9 \\
   \end{bmatrix}$

3) Is $\ T$ linear? Why ?

*answer* :

  **For T be linear it should satisfy the following properties**  - 
>>
1.   $T ( \overrightarrow x + \overrightarrow  y ) = T \overrightarrow x + T \overrightarrow y $
2.   $T ( c \overrightarrow x  ) = c (T \overrightarrow x )  $ .. Where c is a scalar multiple

---
 *To prove property 1)*
 
 >Let,
 $ \overrightarrow x = \begin{bmatrix} 
 x_1 \\
 x_2 \\
 x_3 \\
 \end{bmatrix}$
,
$ \overrightarrow y = \begin{bmatrix} 
 y_1 \\
 y_2 \\
 y_3 \\
 \end{bmatrix}$

>Computing, 
>>$T \overrightarrow x = 
T \begin{bmatrix} 
 x_1 \\
 x_2 \\
 x_3 \\
 \end{bmatrix}$

>>$T \overrightarrow x =  \begin{bmatrix}
x_1 - 3x_3 \\
x_1 + x_2 - 6x_3 \\
x_2 - 3x_3 \\
x_1 - 3x_3 \\
\end{bmatrix}$  ... **eq(1)**

>Similarly,

>>$T \overrightarrow y =
T \begin{bmatrix} 
 y_1 \\
 y_2 \\
 y_3 \\
 \end{bmatrix}$

>>$T \overrightarrow y =
\begin{bmatrix}
y_1 - 3y_3 \\
y_1 + y_2 - 6y_3 \\
y_2 - 3y_3 \\
y_1 - 3y_3 \\
\end{bmatrix}$     ... **eq(2)**

Therefore, RHS should be

>$= T \overrightarrow x + T \overrightarrow y$ 

>$= \begin{bmatrix}
x_1 - 3x_3 \\
x_1 + x_2 - 6x_3 \\
x_2 - 3x_3 \\
x_1 - 3x_3 \\
\end{bmatrix}
+
\begin{bmatrix}
y_1 - 3y_3 \\
y_1 + y_2 - 6y_3 \\
y_2 - 3y_3 \\
y_1 - 3y_3 \\
\end{bmatrix}$  ... **From eq (1) and eq (2)**

>$T \overrightarrow x + T \overrightarrow y = 
\begin{bmatrix}
x_1 - 3x_3 + y_1 - 3y_3\\
x_1 + x_2 - 6x_3 + y_1 + y_2 - 6y_3 \\
x_2 - 3x_3 + y_2 - 3y_3 \\
x_1 - 3x_3 + y_1 - 3y_3 \\
\end{bmatrix}$

>$T \overrightarrow x + T \overrightarrow y = 
\begin{bmatrix}
(x_1 + y_1) - 3(x_3  + y_3)\\
(x_1 + y_1) + (x_2 + y_2) - 6 (x_3  + y_3) \\
(x_2 + y_2) - 3 (x_3 + y_3) \\
(x_1 + y_1) - 3 (x_3 + y_3) \\
\end{bmatrix}$.   .... **eq(3)**


Computing LHS,

>$ =  T ( \overrightarrow x + \overrightarrow  y ) $

>$ =  T 
  \begin{bmatrix}
 x_1 \\
 x_2 \\
 x_3 \\
\end{bmatrix} 
+ 
\begin{bmatrix}
 y_1 \\
 y_2 \\
 y_3 \\
\end{bmatrix} $

>$ = T
   \begin{bmatrix}
   x_1 + y_1  \\
   x_2 + y_2 \\
  x_3 + y_3 \\
  \end{bmatrix}$

>$ = 
 \begin{bmatrix}
   (x_1 + y_1) - 3 (x_3 + y_3)  \\
   (x_1 + y_1) + (x_2 + y_2) - 6(x_3 + y_3) \\
  (x_2 + y_2) -3(x_3 + y_3) \\
  (x_1 + y_1) - 3(x_3 + y_3) \\
  \end{bmatrix}$.  ... **eq(4)**

  *Comparing eq(3) and eq(4)*,
  >>**LHS = RHS**

  >>**Hence property 1) proved**

 *To prove property 2)*
 >Let,
 $ \overrightarrow x = \begin{bmatrix} 
 x_1 \\
 x_2 \\
 x_3 \\
 \end{bmatrix}$

 >Multiplying above vector x with scalar multiple c,

>$ c \overrightarrow x 
= c
\begin{bmatrix} 
 x_1 \\
 x_2 \\
 x_3 \\
 \end{bmatrix}
=
\begin{bmatrix} 
 cx_1 \\
 cx_2 \\
 cx_3 \\
 \end{bmatrix}$

 >Computing,

 >$T ( c \overrightarrow x  ) 
 =
 T 
 \begin{bmatrix} 
 cx_1 \\
 cx_2 \\
 cx_3 \\
 \end{bmatrix}$
 
>>>$ =
 \begin{bmatrix}
  cx_1 - 3cx_3 \\
  cx_1 + cx_2 - 6cx_3 \\
  cx_2 - 3cx_3 \\
  cx_1 - 3cx_3 \\
  \end{bmatrix}
$

 $
 =
 c
 \begin{bmatrix}
x_1 - 3x_3 \\
x_1 + x_2 - 6x_3 \\
x_2 - 3x_3 \\
x_1 - 3x_3 \\
\end{bmatrix}
 $

 $T 
 \begin{bmatrix} 
 cx_1 \\
 cx_2 \\
 cx_3 \\
 \end{bmatrix}
 =
c (T \overrightarrow x)$

Therefore,

$T ( c \overrightarrow x  ) = c (T \overrightarrow x )  $ .. Where c is a scalar multiple.
 **Hence characteristic 2) proved**

 **Hence $T$ is linear**

### Problem 2
--------------

Consider the following function of $x = (x1, x2, x3, x4, x5, x6)$:

$$
f(x) = \sigma \Big(\log \Big(5  \Big(max\{x_1, x_2\}.\frac{x_3}{x_4} - (x_5+x_6) \Big) \Big) + \frac{1}{2} \Big)
$$

where $\sigma$ is the sigmoid function

$$
  \sigma(x) = \frac{1}{1+e^{-x}}
$$

Compute the gradient $\nabla_x f$ and evaluate it at $x = (-1, 3, 4, 5, -5, 7)$

*answer* :

Given:

$$
f(x) = \sigma \Big(\log \Big(5  \Big(max\{x_1, x_2\}.\frac{x_3}{x_4} - (x_5+x_6) \Big) \Big) + \frac{1}{2} \Big)
$$

where,

$$
  \sigma(x) = \frac{1}{1+e^{-x}}
$$

Let,

$$ p = max\{x_1, x_2\}.\frac{x_3}{x_4} - (x_5+x_6)$$

$$ s= log (5p) + \frac {1}{2}$$


*Therefore,* $$f(x) = \sigma (s)$$

$$\nabla_x f =\frac{\partial (\sigma (s))}{\partial s}. \frac {\partial s}{\partial x}$$

$$\nabla_x f = \sigma (s) \Big(1- \sigma (s)\Big) .\frac{\partial \Big(log (5p) + \frac {1}{2}\Big)}{\partial p} . \frac {\partial p}{\partial x}$$

$$\nabla_x f = \frac {\sigma (s) \Big(1- \sigma (s)\Big) }{p}  . \frac {\partial p}{\partial x}$$

*To compute* $ \frac {\partial p}{\partial x}$,
where,
$$ p = max\{x_1, x_2\}.\frac{x_3}{x_4} - (x_5+x_6)$$

**Since we will be calculating x at the point $x = (-1, 3, 4, 5, -5, 7); x_1 < x_2 $**
*Therefore,*
$$ \frac {\partial p}{\partial x_1} = 0 $$
$$ \frac {\partial p}{\partial x_2} = \frac {x_3}{x_4} $$
$$ \frac {\partial p}{\partial x_3} = \frac {max\{x_1, x_2\}}{x_4} $$
$$ \frac {\partial p}{\partial x_4} = max\{x_1, x_2\}.x_3.\frac {-1}{x_4^2} $$
$$ \frac {\partial p}{\partial x_5} = -1 $$
$$ \frac {\partial p}{\partial x_6} = -1 $$


*Combining all the equations and substituting  we get,  $x = (-1, 3, 4, 5, -5, 7)$*
$$ \frac {\partial s}{\partial x_1} = \frac {\sigma (s) \Big(1- \sigma (s)\Big) }{p}  .0 = 0 $$


$$ \frac {\partial s}{\partial x_2} = \frac {\sigma (s) \Big(1- \sigma (s)\Big) }{max\{-1, 3\}.\frac{4}{5} - (-5+7)}  .\frac {4}{5} $$

$$ \frac {\partial s}{\partial x_2} =  \frac {\sigma (s) \Big(1- \sigma (s)\Big) }{\frac{2}{5}}  .\frac {4}{5} =  \sigma (s) \Big(1- \sigma (s)\Big) . 2 = 2 (0.1785489) = 0.357097$$


$$ \frac {\partial s}{\partial x_3} = \frac {\sigma (s) \Big(1- \sigma (s)\Big) }{p} . \frac {max\{-1, 3\}}{5} = \frac{0.1785489} {\frac{2}{5}} .  \frac {3}{5} =  0.26782327$$


$$ \frac {\partial s}{\partial x_4} = \frac {\sigma (s) \Big(1- \sigma (s)\Big) }{p} .max\{x_1, x_2\}.x_3.\frac {-1}{x_4^2} $$
$$ \frac {\partial s}{\partial x_4} = \frac{0.1785489} {\frac{2}{5}} . max\{-1, 3\} . 4 = -0.21426 $$


$$ \frac {\partial s}{\partial x_5} = \frac {\sigma (s) \Big(1- \sigma (s)\Big) }{p} . -1  = -0.446327$$


$$ \frac {\partial s}{\partial x_6} = = \frac {\sigma (s) \Big(1- \sigma (s)\Big) }{p} . -1  = -0.446327$$ $$


Where,

$$ \sigma (s) \Big(1- \sigma (s) \Big)= 0.1785489$$



**Final Answer**
$$ \Big[ 0, 0.357097, 0.26782327, −0.21426, −0.446327, −0.446327 \Big]$$


### Problem 3
-------------

$a = [2, 6, 1, 9, 10, 3, 27, 5, 7, 14, 24, 3]$

Get all items in range $(5, 10]$ from $a$

Note: Use only indexing methods, do not use iteration or if conditions

In [ ]:
import numpy as np
## write your code under this line:
#----------------------------------
a = np.array([2,6,1,9,10,3,27,5,7,14,24,3])
a_mask = np.array(np.where((a>5) & (a<=10), 1,0), dtype=bool)
a[a_mask]

array([ 6,  9, 10,  7])

### Problem 4
--------------

Let 

$$x = [3, 4, 5]$$


$$W = \begin{bmatrix} 1 & 5 & 3 \\ 2 & 5 & 5 \\5 & 5 &1 \end{bmatrix}$$

Compute


1) $x^T$

In [ ]:
## write your code under this line:
#----------------------------------
x = np.array([3,4,5])
W = np.array([[1,5,3],[2,5,5],[5,5,1]])

x_t = np.transpose(x)
x_t

array([3, 4, 5])

2) $z = Wx^T$

In [ ]:
## write your code under this line:
#----------------------------------
z = np.matmul(W,x_t)
z

array([38, 51, 40])

3) Write a function softmax:
$$
  softmax(x)_i = \frac{e^{x_i}}{\sum_j e^{x_j}}
$$


In [ ]:
def softmax(x):
  # x is a numpy array of length 3
  ## write your code under this line:
  #----------------------------------
  res = np.exp(x)/np.exp(x).sum()
  return res  # return correct result




compute $softmax(z)$ :

In [ ]:
## write your code under this line:
#----------------------------------
softmax(z)

array([2.26028655e-06, 9.99981038e-01, 1.67013841e-05])

----------------------------